### ISSUE TITLE
Game crash when playing around with blue wire and covers

### ISSUE THREAD

**Issue by Crazy-KSK** [Qmunity/BluePower#295] opened 2015-02-21 18:44 UTC
I broke a block in something very close to  this although I cant seem to make it happen again
http://i.imgur.com/fdGXU5K.png
and got this
http://pastebin.com/hLLb4BMX

PS: I noticed a lot of strange behavior when playing around with that setup in the picture
sync issues and wires not connecting the same way every time they are placed

**Comment by Crazy-KSK** [comment] 2015-02-21 18:54
edit doesn't work for some reason 
http://i.imgur.com/ROG18Zj.png remove and replace wire the arrow points at and it crashes

**Comment by amadornes** [comment] 2015-02-21 19:37
Shoud be fixed in the next update. The wires have rewritten.
Those sync issues are caused by FMP and QmunityLib's part systems not working very well alongside eachother but that's fixed now.
It should be fixed in the next build we push out to CurseForge :)

**Closed** 2015-02-24 08:47 UTC
Labels: Fixed. Pending release
