### ISSUE TITLE
Update Crash

### ISSUE THREAD

**Issue by Chocohead** [Qmunity/BluePower#236] opened 2015-01-01 15:22 UTC
I tried to update to the latest Bluepower, but when I try to load my previous world, I crash with this every time: http://pastebin.com/pQ2iyERn

**Comment by amadornes** [comment] 2015-01-01 16:16
That's a weird crash... It seems to be caused by the world converter when trying to move from the old part system to the new one. I had that crash the other day and I thought I fixed it...
I'll take a look at it and see what I can do to fix it. It shouldn't be *too* hard

**Comment by amadornes** [comment] 2015-01-03 00:25
Fixed it yesterday and forgot to close the issue xP

**Closed by amadornes** 2015-01-03 00:25 UTC
Labels: Bug
