### ISSUE TITLE
interaction with blue power 

### ISSUE THREAD

**Issue by skuff84** [Qmunity/BluePower#276] opened 2015-01-26 04:52 UTC
If you interact with and of the pneumatic tubes, and or sorting machines, while there working it is causing a major server shutdown, and I have to keep using backups if I try to move a tube wile inventory is in it.

**Comment by Quetzi** [comment] 2015-01-26 10:29
Do you have a crash log for this crash?

**Comment by skuff84** [comment] 2015-01-26 14:32
I don't, I tried to get on put on

**Comment by skuff84** [comment] 2015-01-26 14:35
I don't, I have tried a few time to get his posted but it would error out on me, its very easy to duplicate, just hook up a sorting machine with some tubes, when its trying to sort inventory break a tube or the machine itself, it will crash, just noticed ticket 272 is having the same problem, they just haven't figured it out yet

**Comment by skuff84** [comment] 2015-01-26 15:27
I have a crash log but its in .RAR file type, is there an e-mail I can send this to u?

**Comment by Quetzi** [comment] 2015-01-29 09:54
Closing as probably a duplicate of #272 which we're hoping to solve soon

**Closed by Quetzi** 2015-01-29 09:54 UTC
Labels: Bug, Confirmed, Duplicate
