### ISSUE TITLE
Incredibly long load times?

### ISSUE THREAD

**Issue by SheldonCurtiss** [Qmunity/BluePower#586] opened 2021-07-30 20:37 UTC
Bluepower takes longer than anything during startup, I've seen this issue on multiple versions.
Why is this?
I do have tons of mods but like I said I've seen this on multiple versions of mc
 
  Total Time
      bluepower: 80317ms

### Forge and Minecraft version ###
Forge: Newest
Minecraft: 1.12.2
BluePower-1.12.2-0.3.152-universal.jar

**Comment by MoreThanHidden** [comment] 2021-08-01 08:58
Duplicate of #574 known issue, working on moving Furnace Data pack to Dynamic Recipes similar to how micro-blocks are handled  until then can disable recycling recipes in the config:
```toml
#Generate Json Datapack for Alloy Furnace (Only used to generate recycling recipes)
	alloyFurnaceDatapackGenerator = false
```

**Closed** 2021-08-21 16:33 UTC
Labels: Duplicate, Pending fix, Planned Feature
