### ISSUE TITLE
Startup crash

### ISSUE THREAD

**Issue by topher2010** [Qmunity/BluePower#407] opened 2015-09-13 17:16 UTC
This only happens when Magneticraft is updated to it's latest build, 0.4.6.  I'll post an issue for them as well.  I get the following crash report:

http://pastebin.com/V2iAVL9A

**Comment by TheJulianJES** [comment] 2015-09-13 17:35
Duplicate of #406

**Comment by MoreThanHidden** [comment] 2019-03-16 06:07
As stated previously is a duplicate of #406

**Closed by MoreThanHidden** 2019-03-16 06:07 UTC
