### ISSUE TITLE
Weird texture on gates

### ISSUE THREAD

**Issue by 88Void88** [Qmunity/BluePower#341] opened 2015-04-29 04:30 UTC
The sides of a gate doesn't have a texture and when placed on the side of the block the texture will look dark (weird lighting)
![2015-04-29_11 28 56](https://cloud.githubusercontent.com/assets/12163453/7384736/233b620c-ee63-11e4-9594-e75e2f519dcd.png)

**Comment by amadornes** [comment] 2015-04-29 14:18
The texture issue is caused by your texturepack. @CyanideX hasn't updated the BP textures in a while and some of them are incompatible with the newest versions.
In terms of the lighting: that happened up until a couple of versions ago. It should be fixed in the latest one :)

**Closed by amadornes** 2015-04-29 14:18 UTC
