### ISSUE TITLE
java.lang.NullPointerException: Ticking player

### ISSUE THREAD

**Issue by Sailren** [Qmunity/BluePower#251] opened 2015-01-06 20:43 UTC
this crash happened, when i held a gate in my hand and hovering over an already placed gate

http://paste.ubuntu.com/9684165/

**Comment by nanakisan** [comment] 2015-01-07 02:57
Strange as the thing causing the player tick handling is coming from MiscUtils. Do you know if any mods in that modpack yer using require that mod as a library? Certainly isn't BP as it's only core dependency is QMunitylib.

**Comment by amadornes** [comment] 2015-01-07 09:06
The crash is indeed being caused by MiscUtils, because that case scenario that's shown above the MU calls shouldn't ever happen with vanilla BluePower+QLib. I will reinforce the null-checks so we are sure that can never happen, but I cannot assure it'll fix it

**Comment by Sailren** [comment] 2015-01-07 09:08
no problem, but weird that miscutils is causing it and bluepower+lib show up in crash report

**Comment by nanakisan** [comment] 2015-01-07 10:43
A stack trace will always try too show you just how deep is the issue. It's why they're soo essential when bugs are found.

**Comment by amadornes** [comment] 2015-02-08 20:09
I guess this has been fixed or it causes no more issues?

**Comment by Sailren** [comment] 2015-02-08 23:05
no idea, i removed the faulty mod, but  i think yes, anyway my client is similar to ftb ultimate, not quite like ftb ressurection but yeah

**Comment by amadornes** [comment] 2015-02-09 16:46
Closing this, then :P

**Closed by amadornes** 2015-02-09 16:46 UTC
