### ISSUE TITLE
project table/ regulator item inserting

### ISSUE THREAD

**Issue by Kropter** [Qmunity/BluePower#207] opened 2014-11-16 09:37 UTC
Project Table:
When having items in the crafting grid and pushing X, the items will be placed in the first empty spot, they don't check if there is already a stack of the same item. Sso you can have multiple little stacks of the same item.
Its not really a bug, but an annoyance because a really full project table you have to check for multiple stacks when you run out of an resource and emptied the crafting grid.

Regulator: Basically the same, it fills the first empty spot. When in supply mode with multiple items and the Regulator pushes something out, the next item incoming will be placed on the empty spot. Especially difficult when you have a lot of different items in one regulator setup, because it then sometimes is not accepting the intended items because all 9 spaces are full.

**Comment by amadornes** [comment] 2015-01-07 12:56
Somebody PR'ed a fix for this the other day, though it only affects the Project Table. I'll port the code over to the regulator (and the IO Helper, actually). In theory even tubes should do it as it is now

**Comment by MineMaarten** [comment] 2015-01-14 15:41
We've discussed that the insertion of the Regulator (and any other inserting method for that matter) is wanted behaviour, and not a bug. It's consistent with Vanilla insertion (hopper does the same), and with like 99% of modded insertion techniques.

**Closed by MineMaarten** 2015-01-14 15:41 UTC
Labels: Bug, Confirmed, Minor
